# Theme and Plugins
remote_theme: pages-themes/midnight@v0.2.0
plugins:
 - jekyll-remote-theme
# Repository Metadata
title: "Healthcare Data Analysis"
description: "A Power BI dashboard providing insights into unique patient records from 10 major hospitals across the U.S"
author: "Jan Aeron Abrahan"
github_username: "aeronabrahan"
# Navigation Settings
show_downloads: true
include:
 - README.md
 - assets/datasets
 - assets/images
 - assets/pbi
# Repository Settings
repository: "aeronabrahan/Healthcare-Analysis"
url: "https://github.com/aeronabrahan/Healthcare-Analysis"
# SEO and Social Sharing
social:
 name: "Jan Aeron Abrahan"
 links:
   - "https://github.com/aeronabrahan"
   - "https://linkedin.com/in/jagabrahan"
# Custom Options
markdown: kramdown
permalink: pretty
